/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as RShareTokenRouteImport } from './routes/r/$shareToken'
import { Route as LoginCodeRouteImport } from './routes/login_.code'
import { Route as ApplyApplyTokenRouteImport } from './routes/apply.$applyToken'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppMeRouteImport } from './routes/app/me'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as STokenRouteRouteImport } from './routes/s/$token/route'
import { Route as AppOrgSlugRouteRouteImport } from './routes/app/$orgSlug/route'
import { Route as STokenIndexRouteImport } from './routes/s/$token/index'
import { Route as AppOrgSlugIndexRouteImport } from './routes/app/$orgSlug/index'
import { Route as STokenPrivacyRouteImport } from './routes/s/$token/privacy'
import { Route as STokenInterviewRouteImport } from './routes/s/$token/interview'
import { Route as STokenDoneRouteImport } from './routes/s/$token/done'
import { Route as STokenCheckRouteImport } from './routes/s/$token/check'
import { Route as AppOrgSlugChangelogRouteImport } from './routes/app/$orgSlug/changelog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrgSlugSettingsRouteRouteImport } from './routes/app/$orgSlug/settings/route'
import { Route as AppOrgSlugSettingsIndexRouteImport } from './routes/app/$orgSlug/settings/index'
import { Route as AppOrgSlugProjectsIndexRouteImport } from './routes/app/$orgSlug/projects.index'
import { Route as AppOrgSlugSettingsMembersRouteImport } from './routes/app/$orgSlug/settings/members'
import { Route as AppOrgSlugSettingsInvitationsRouteImport } from './routes/app/$orgSlug/settings/invitations'
import { Route as AppOrgSlugSettingsGeneralRouteImport } from './routes/app/$orgSlug/settings/general'
import { Route as AppOrgSlugProjectsNewRouteImport } from './routes/app/$orgSlug/projects.new'
import { Route as AppOrgSlugCandidatesSessionIdRouteImport } from './routes/app/$orgSlug/candidates.$sessionId'
import { Route as AppOrgSlugProjectsProjectSlugIndexRouteImport } from './routes/app/$orgSlug/projects.$projectSlug.index'
import { Route as AppOrgSlugProjectsProjectSlugEditRouteImport } from './routes/app/$orgSlug/projects.$projectSlug.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const RShareTokenRoute = RShareTokenRouteImport.update({
  id: '/r/$shareToken',
  path: '/r/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCodeRoute = LoginCodeRouteImport.update({
  id: '/login_/code',
  path: '/login/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyApplyTokenRoute = ApplyApplyTokenRouteImport.update({
  id: '/apply/$applyToken',
  path: '/apply/$applyToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRouteRoute = STokenRouteRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugRouteRoute = AppOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const STokenIndexRoute = STokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => STokenRouteRoute,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const STokenPrivacyRoute = STokenPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => STokenRouteRoute,
} as any)
const STokenInterviewRoute = STokenInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => STokenRouteRoute,
} as any)
const STokenDoneRoute = STokenDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => STokenRouteRoute,
} as any)
const STokenCheckRoute = STokenCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => STokenRouteRoute,
} as any)
const AppOrgSlugChangelogRoute = AppOrgSlugChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugSettingsRouteRoute = AppOrgSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugSettingsIndexRoute = AppOrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugSettingsRouteRoute,
} as any)
const AppOrgSlugProjectsIndexRoute = AppOrgSlugProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugSettingsMembersRoute =
  AppOrgSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugSettingsInvitationsRoute =
  AppOrgSlugSettingsInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugSettingsGeneralRoute =
  AppOrgSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugProjectsNewRoute = AppOrgSlugProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugCandidatesSessionIdRoute =
  AppOrgSlugCandidatesSessionIdRouteImport.update({
    id: '/candidates/$sessionId',
    path: '/candidates/$sessionId',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugIndexRoute =
  AppOrgSlugProjectsProjectSlugIndexRouteImport.update({
    id: '/projects/$projectSlug/',
    path: '/projects/$projectSlug/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugProjectsProjectSlugEditRoute =
  AppOrgSlugProjectsProjectSlugEditRouteImport.update({
    id: '/projects/$projectSlug/edit',
    path: '/projects/$projectSlug/edit',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/account-deletion': typeof AccountDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/s/$token': typeof STokenRouteRouteWithChildren
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/apply/$applyToken': typeof ApplyApplyTokenRoute
  '/login/code': typeof LoginCodeRoute
  '/r/$shareToken': typeof RShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/s/$token/check': typeof STokenCheckRoute
  '/s/$token/done': typeof STokenDoneRoute
  '/s/$token/interview': typeof STokenInterviewRoute
  '/s/$token/privacy': typeof STokenPrivacyRoute
  '/app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/s/$token/': typeof STokenIndexRoute
  '/app/$orgSlug/candidates/$sessionId': typeof AppOrgSlugCandidatesSessionIdRoute
  '/app/$orgSlug/projects/new': typeof AppOrgSlugProjectsNewRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/projects/': typeof AppOrgSlugProjectsIndexRoute
  '/app/$orgSlug/settings/': typeof AppOrgSlugSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug/edit': typeof AppOrgSlugProjectsProjectSlugEditRoute
  '/app/$orgSlug/projects/$projectSlug/': typeof AppOrgSlugProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/apply/$applyToken': typeof ApplyApplyTokenRoute
  '/login/code': typeof LoginCodeRoute
  '/r/$shareToken': typeof RShareTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/s/$token/check': typeof STokenCheckRoute
  '/s/$token/done': typeof STokenDoneRoute
  '/s/$token/interview': typeof STokenInterviewRoute
  '/s/$token/privacy': typeof STokenPrivacyRoute
  '/app/$orgSlug': typeof AppOrgSlugIndexRoute
  '/s/$token': typeof STokenIndexRoute
  '/app/$orgSlug/candidates/$sessionId': typeof AppOrgSlugCandidatesSessionIdRoute
  '/app/$orgSlug/projects/new': typeof AppOrgSlugProjectsNewRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/projects': typeof AppOrgSlugProjectsIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug/edit': typeof AppOrgSlugProjectsProjectSlugEditRoute
  '/app/$orgSlug/projects/$projectSlug': typeof AppOrgSlugProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/account-deletion': typeof AccountDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/s/$token': typeof STokenRouteRouteWithChildren
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/apply/$applyToken': typeof ApplyApplyTokenRoute
  '/login_/code': typeof LoginCodeRoute
  '/r/$shareToken': typeof RShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/s/$token/check': typeof STokenCheckRoute
  '/s/$token/done': typeof STokenDoneRoute
  '/s/$token/interview': typeof STokenInterviewRoute
  '/s/$token/privacy': typeof STokenPrivacyRoute
  '/app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/s/$token/': typeof STokenIndexRoute
  '/app/$orgSlug/candidates/$sessionId': typeof AppOrgSlugCandidatesSessionIdRoute
  '/app/$orgSlug/projects/new': typeof AppOrgSlugProjectsNewRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/projects/': typeof AppOrgSlugProjectsIndexRoute
  '/app/$orgSlug/settings/': typeof AppOrgSlugSettingsIndexRoute
  '/app/$orgSlug/projects/$projectSlug/edit': typeof AppOrgSlugProjectsProjectSlugEditRoute
  '/app/$orgSlug/projects/$projectSlug/': typeof AppOrgSlugProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/account-deletion'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/$orgSlug'
    | '/s/$token'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/apply/$applyToken'
    | '/login/code'
    | '/r/$shareToken'
    | '/app/'
    | '/app/$orgSlug/settings'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/s/$token/check'
    | '/s/$token/done'
    | '/s/$token/interview'
    | '/s/$token/privacy'
    | '/app/$orgSlug/'
    | '/s/$token/'
    | '/app/$orgSlug/candidates/$sessionId'
    | '/app/$orgSlug/projects/new'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/projects/'
    | '/app/$orgSlug/settings/'
    | '/app/$orgSlug/projects/$projectSlug/edit'
    | '/app/$orgSlug/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/apply/$applyToken'
    | '/login/code'
    | '/r/$shareToken'
    | '/app'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/s/$token/check'
    | '/s/$token/done'
    | '/s/$token/interview'
    | '/s/$token/privacy'
    | '/app/$orgSlug'
    | '/s/$token'
    | '/app/$orgSlug/candidates/$sessionId'
    | '/app/$orgSlug/projects/new'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/projects'
    | '/app/$orgSlug/settings'
    | '/app/$orgSlug/projects/$projectSlug/edit'
    | '/app/$orgSlug/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/account-deletion'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/$orgSlug'
    | '/s/$token'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/apply/$applyToken'
    | '/login_/code'
    | '/r/$shareToken'
    | '/app/'
    | '/app/$orgSlug/settings'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/s/$token/check'
    | '/s/$token/done'
    | '/s/$token/interview'
    | '/s/$token/privacy'
    | '/app/$orgSlug/'
    | '/s/$token/'
    | '/app/$orgSlug/candidates/$sessionId'
    | '/app/$orgSlug/projects/new'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/projects/'
    | '/app/$orgSlug/settings/'
    | '/app/$orgSlug/projects/$projectSlug/edit'
    | '/app/$orgSlug/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AccountDeletionRoute: typeof AccountDeletionRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  STokenRouteRoute: typeof STokenRouteRouteWithChildren
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  ApplyApplyTokenRoute: typeof ApplyApplyTokenRoute
  LoginCodeRoute: typeof LoginCodeRoute
  RShareTokenRoute: typeof RShareTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/r/$shareToken': {
      id: '/r/$shareToken'
      path: '/r/$shareToken'
      fullPath: '/r/$shareToken'
      preLoaderRoute: typeof RShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/code': {
      id: '/login_/code'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$applyToken': {
      id: '/apply/$applyToken'
      path: '/apply/$applyToken'
      fullPath: '/apply/$applyToken'
      preLoaderRoute: typeof ApplyApplyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug': {
      id: '/app/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/s/$token/': {
      id: '/s/$token/'
      path: '/'
      fullPath: '/s/$token/'
      preLoaderRoute: typeof STokenIndexRouteImport
      parentRoute: typeof STokenRouteRoute
    }
    '/app/$orgSlug/': {
      id: '/app/$orgSlug/'
      path: '/'
      fullPath: '/app/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/s/$token/privacy': {
      id: '/s/$token/privacy'
      path: '/privacy'
      fullPath: '/s/$token/privacy'
      preLoaderRoute: typeof STokenPrivacyRouteImport
      parentRoute: typeof STokenRouteRoute
    }
    '/s/$token/interview': {
      id: '/s/$token/interview'
      path: '/interview'
      fullPath: '/s/$token/interview'
      preLoaderRoute: typeof STokenInterviewRouteImport
      parentRoute: typeof STokenRouteRoute
    }
    '/s/$token/done': {
      id: '/s/$token/done'
      path: '/done'
      fullPath: '/s/$token/done'
      preLoaderRoute: typeof STokenDoneRouteImport
      parentRoute: typeof STokenRouteRoute
    }
    '/s/$token/check': {
      id: '/s/$token/check'
      path: '/check'
      fullPath: '/s/$token/check'
      preLoaderRoute: typeof STokenCheckRouteImport
      parentRoute: typeof STokenRouteRoute
    }
    '/app/$orgSlug/changelog': {
      id: '/app/$orgSlug/changelog'
      path: '/changelog'
      fullPath: '/app/$orgSlug/changelog'
      preLoaderRoute: typeof AppOrgSlugChangelogRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug/settings': {
      id: '/app/$orgSlug/settings'
      path: '/settings'
      fullPath: '/app/$orgSlug/settings'
      preLoaderRoute: typeof AppOrgSlugSettingsRouteRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/settings/': {
      id: '/app/$orgSlug/settings/'
      path: '/'
      fullPath: '/app/$orgSlug/settings/'
      preLoaderRoute: typeof AppOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/projects/': {
      id: '/app/$orgSlug/projects/'
      path: '/projects'
      fullPath: '/app/$orgSlug/projects/'
      preLoaderRoute: typeof AppOrgSlugProjectsIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/settings/members': {
      id: '/app/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/app/$orgSlug/settings/members'
      preLoaderRoute: typeof AppOrgSlugSettingsMembersRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/settings/invitations': {
      id: '/app/$orgSlug/settings/invitations'
      path: '/invitations'
      fullPath: '/app/$orgSlug/settings/invitations'
      preLoaderRoute: typeof AppOrgSlugSettingsInvitationsRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/settings/general': {
      id: '/app/$orgSlug/settings/general'
      path: '/general'
      fullPath: '/app/$orgSlug/settings/general'
      preLoaderRoute: typeof AppOrgSlugSettingsGeneralRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/projects/new': {
      id: '/app/$orgSlug/projects/new'
      path: '/projects/new'
      fullPath: '/app/$orgSlug/projects/new'
      preLoaderRoute: typeof AppOrgSlugProjectsNewRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/candidates/$sessionId': {
      id: '/app/$orgSlug/candidates/$sessionId'
      path: '/candidates/$sessionId'
      fullPath: '/app/$orgSlug/candidates/$sessionId'
      preLoaderRoute: typeof AppOrgSlugCandidatesSessionIdRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/projects/$projectSlug/': {
      id: '/app/$orgSlug/projects/$projectSlug/'
      path: '/projects/$projectSlug'
      fullPath: '/app/$orgSlug/projects/$projectSlug/'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/projects/$projectSlug/edit': {
      id: '/app/$orgSlug/projects/$projectSlug/edit'
      path: '/projects/$projectSlug/edit'
      fullPath: '/app/$orgSlug/projects/$projectSlug/edit'
      preLoaderRoute: typeof AppOrgSlugProjectsProjectSlugEditRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
  }
}

interface AppOrgSlugSettingsRouteRouteChildren {
  AppOrgSlugSettingsGeneralRoute: typeof AppOrgSlugSettingsGeneralRoute
  AppOrgSlugSettingsInvitationsRoute: typeof AppOrgSlugSettingsInvitationsRoute
  AppOrgSlugSettingsMembersRoute: typeof AppOrgSlugSettingsMembersRoute
  AppOrgSlugSettingsIndexRoute: typeof AppOrgSlugSettingsIndexRoute
}

const AppOrgSlugSettingsRouteRouteChildren: AppOrgSlugSettingsRouteRouteChildren =
  {
    AppOrgSlugSettingsGeneralRoute: AppOrgSlugSettingsGeneralRoute,
    AppOrgSlugSettingsInvitationsRoute: AppOrgSlugSettingsInvitationsRoute,
    AppOrgSlugSettingsMembersRoute: AppOrgSlugSettingsMembersRoute,
    AppOrgSlugSettingsIndexRoute: AppOrgSlugSettingsIndexRoute,
  }

const AppOrgSlugSettingsRouteRouteWithChildren =
  AppOrgSlugSettingsRouteRoute._addFileChildren(
    AppOrgSlugSettingsRouteRouteChildren,
  )

interface AppOrgSlugRouteRouteChildren {
  AppOrgSlugSettingsRouteRoute: typeof AppOrgSlugSettingsRouteRouteWithChildren
  AppOrgSlugChangelogRoute: typeof AppOrgSlugChangelogRoute
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
  AppOrgSlugCandidatesSessionIdRoute: typeof AppOrgSlugCandidatesSessionIdRoute
  AppOrgSlugProjectsNewRoute: typeof AppOrgSlugProjectsNewRoute
  AppOrgSlugProjectsIndexRoute: typeof AppOrgSlugProjectsIndexRoute
  AppOrgSlugProjectsProjectSlugEditRoute: typeof AppOrgSlugProjectsProjectSlugEditRoute
  AppOrgSlugProjectsProjectSlugIndexRoute: typeof AppOrgSlugProjectsProjectSlugIndexRoute
}

const AppOrgSlugRouteRouteChildren: AppOrgSlugRouteRouteChildren = {
  AppOrgSlugSettingsRouteRoute: AppOrgSlugSettingsRouteRouteWithChildren,
  AppOrgSlugChangelogRoute: AppOrgSlugChangelogRoute,
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
  AppOrgSlugCandidatesSessionIdRoute: AppOrgSlugCandidatesSessionIdRoute,
  AppOrgSlugProjectsNewRoute: AppOrgSlugProjectsNewRoute,
  AppOrgSlugProjectsIndexRoute: AppOrgSlugProjectsIndexRoute,
  AppOrgSlugProjectsProjectSlugEditRoute:
    AppOrgSlugProjectsProjectSlugEditRoute,
  AppOrgSlugProjectsProjectSlugIndexRoute:
    AppOrgSlugProjectsProjectSlugIndexRoute,
}

const AppOrgSlugRouteRouteWithChildren = AppOrgSlugRouteRoute._addFileChildren(
  AppOrgSlugRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppOrgSlugRouteRoute: typeof AppOrgSlugRouteRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  AppMeRoute: typeof AppMeRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrgSlugRouteRoute: AppOrgSlugRouteRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  AppMeRoute: AppMeRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface STokenRouteRouteChildren {
  STokenCheckRoute: typeof STokenCheckRoute
  STokenDoneRoute: typeof STokenDoneRoute
  STokenInterviewRoute: typeof STokenInterviewRoute
  STokenPrivacyRoute: typeof STokenPrivacyRoute
  STokenIndexRoute: typeof STokenIndexRoute
}

const STokenRouteRouteChildren: STokenRouteRouteChildren = {
  STokenCheckRoute: STokenCheckRoute,
  STokenDoneRoute: STokenDoneRoute,
  STokenInterviewRoute: STokenInterviewRoute,
  STokenPrivacyRoute: STokenPrivacyRoute,
  STokenIndexRoute: STokenIndexRoute,
}

const STokenRouteRouteWithChildren = STokenRouteRoute._addFileChildren(
  STokenRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AccountDeletionRoute: AccountDeletionRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  STokenRouteRoute: STokenRouteRouteWithChildren,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  ApplyApplyTokenRoute: ApplyApplyTokenRoute,
  LoginCodeRoute: LoginCodeRoute,
  RShareTokenRoute: RShareTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
